language: generic
env:
  - MAX_OLD_SPACE_SIZE=4096

before_install:
- npm i serverless -g
- serverless config credentials --provider aws --key ${AWS_ACCESS_KEY_ID} --secret ${AWS_SECRET_KEY}
- ls
- chmod +x ./backend/deploy.sh

stages:
- name: Deploy Dev
  if: branch = dev
- name: Deploy Prod
  if: branch = main

jobs: 
  include:
    - stage:  Deploy Dev
      script: ./backend/deploy.sh
    - stage:  Deploy Prod
      script: ./backend/deploy.sh